# Generated by Django 4.0.4 on 2022-05-08 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskfield',
            name='title',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='workfield',
            name='title',
            field=models.CharField(default='', max_length=200),
        ),
    ]
