# Generated by Django 4.0.4 on 2022-05-09 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_taskfield_title_workfield_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='title',
        ),
    ]
